hydra:
  job:
    chdir: true

dataset:
  path: /home/coled/flow-learning/demonstrations/more_varied/xbox_varied_84.hdf5

training:
  lr: 0.0001
  batch_size: 172
  num_epochs: 1000
  save_freq: 100

flow:
  action_window_size: 8
  obs_window_size: 2