hydra:
  job:
    chdir: true

dataset:
  path: /home/coled/flow-learning/demonstrations/lift_test.hdf5

training:
  lr: 0.001
  batch_size: 64
  num_epochs: 100

flow:
  action_window_size: 8
  obs_window_size: 2